# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python36:
      python.version: '3.6'
      TOX_ENV: py36
    Python37:
      python.version: '3.7'
      TOX_ENV: py37
    Python38:
      python.version: '3.8'
      TOX_ENV: py38

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: pip install tox
  displayName: 'Install Tox'

- script: tox -e $TOX_ENV
  displayName: 'Run tests with Tox'